RESSOURCES_PATH = ".\\res\\"

IMG_CHASSE_TRESOR = RESSOURCES_PATH + "CHASSE.png"
IMG_DEPART = RESSOURCES_PATH + "DEPART.png"
IMG_HINT = RESSOURCES_PATH + "HINT.png"
IMG_LEFT_ARROW = RESSOURCES_PATH + "LEFT_ARROW.png"
IMG_RIGHT_ARROW = RESSOURCES_PATH + "RIGHT_ARROW.png"
IMG_TOP_ARROW = RESSOURCES_PATH + "TOP_ARROW.png"
IMG_BOTTOM_ARROW = RESSOURCES_PATH + "BOTTOM_ARROW.png"
IMG_NEXT = RESSOURCES_PATH + "NEXT.png"
IMG_FIGHT = RESSOURCES_PATH + "FIGHT.png"
IMG_POPO = RESSOURCES_PATH + "popo.png"

IMG_CANCEL_VALIDATION = RESSOURCES_PATH + "cancelHuntValidation.png"
IMG_CANCEL_REJECTED = RESSOURCES_PATH + "cancelHuntRejected.png"
IMG_LEVEL_120 = RESSOURCES_PATH + "missionsLevel120.png"

TMP_SCREENSHOT = ".\\res\\TMP.png"
TMP_IMG_MAIN_REGION = ".\\res\\TMP_MAIN_REGION.png"

POS_ZAAP = [-27,-36]
POS_POPO = (855, 960)
